# Generated by Django 6.0 on 2026-03-11 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Birthday', 'Birthday'), ('Corporate Event', 'Corporate Event'), ('Engagement', 'Engagement'), ('Baby Shower', 'Baby Shower'), ('College Fest', 'College Fest'), ('Anniversary Celebration', 'Anniversary Celebration'), ('House Warming Ceremony', 'House Warming Ceremony'), ('Product Launch Event', 'Product Launch Event'), ('Cultural Events', 'Cultural Events'), ('Music Concert Events', 'Music Concert Events')], max_length=50),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star – Poor'), (2, '2 Stars – Average'), (3, '3 Stars – Good'), (4, '4 Stars – Very Good'), (5, '5 Stars – Excellent')])),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'booking')},
            },
        ),
    ]
