# Generated by Django 6.0 on 2026-03-11 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gallery_image_hash_alter_booking_event_type_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='timeline',
            field=models.JSONField(blank=True, help_text='Auto-generated event timeline', null=True),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('is_checked_in', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='core.booking')),
            ],
        ),
    ]
