# Generated by Django 6.0 on 2026-03-12 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_booking_customer_address_booking_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=255)),
                ('event_title', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_time', models.CharField(max_length=100)),
                ('event_venue', models.TextField()),
                ('message', models.TextField(blank=True, null=True)),
                ('template_choice', models.CharField(choices=[('wedding', 'Wedding Theme'), ('birthday', 'Birthday Theme'), ('corporate', 'Corporate Theme'), ('elegant', 'Elegant Theme'), ('minimal', 'Minimal Theme')], default='elegant', max_length=50)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='invitation_qrs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='core.booking')),
            ],
        ),
    ]
