# Generated by Django 6.0 on 2026-03-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_booking_amount_paid_booking_is_advance_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='package_type',
            field=models.CharField(choices=[('Budget', 'Budget Package'), ('Standard', 'Standard Package'), ('Luxury', 'Luxury Package')], default='Standard', max_length=20),
        ),
    ]
