# Generated by Django 6.0 on 2026-03-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_service_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='package_type',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Standard', 'Standard'), ('Budget', 'Budget')], default='Standard', max_length=20),
        ),
    ]
