# Generated by Django 6.0 on 2026-03-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_service_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='package_type',
            field=models.CharField(choices=[('Budget', 'Budget'), ('Standard', 'Standard'), ('Luxury', 'Luxury')], default='Standard', max_length=20),
        ),
    ]
