# Generated by Django 6.0 on 2026-03-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_service_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Birthday Party', 'Birthday Party'), ('Engagement', 'Engagement'), ('Baby Shower', 'Baby Shower'), ('Corporate Event', 'Corporate Event'), ('Cultural Event', 'Cultural Event'), ('Music Concert', 'Music Concert')], max_length=50),
        ),
    ]
