# Generated by Django 6.0 on 2026-03-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_gallery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_balance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
